tls:
  certificates:
    - certFile: /certs/ssl-bundle.pem
      keyFile: /certs/privatekeymultidominiogetxo.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /certs/ssl-bundle.pem
        keyFile: /certs/privatekeymultidominiogetxo.pem